#!/usr/bin/env bash

# Arch dotfiles setup script
#
# Uses dotbot for dotfile install but this probably will be made into a custom dotfile manager soon
# Also can install needed packages


help() {
	printf "Usage: $0 [OPTIONS] [script names]\n"
	printf "Argurments:\n"
	printf "  [script names]\n\tAn optional list of install scripts to run found in ./installScripts/."
	printf "\n\tTo run these scripts, pass in the '-e' option.\n\n"

	printf "Options:\n"
	printf "  -h\n\tShow this help message and exit\n"
	printf "  -f\n\tSetup the complete system. Equivalent to running $0 -s -p -d\n"
	printf "  -s\n\tConfigure system.\n"
	printf "  -p\n\tInstall system packages\n"
	printf "  -d\n\tInstall dotfiles\n"
	printf "  -e\n\tRun extra install scripts\n"
}

setupSystem() {
	/usr/bin/env bash ./installScripts/system
}

setupPackages() {
	/usr/bin/env bash ./installScripts/packages
}

setupDotfiles() {
	dotbot -c dotbot.conf.yaml
}

doFullInstall() {
	setupSystem
	setupPackages
	setupDotfiles
}

extraScripts=false
while getopts 'hfspde' opt; do
	case "$opt" in
		h) help; exit 0;;
		f) doFullInstall;;
		s) setupSystem;;
		p) setupPackages;;
		d) setupDotfiles;;
		e) extraScripts=true;;
		*) help; exit 1;;
	esac
done

shift $(( OPTIND - 1 ))

if $extraScripts; then
	echo "Running extra scripts..."
	for scriptName in "$@"; do
		/usr/bin/env bash ./installScripts/$scriptName
	done
fi

