#!/usr/bin/env bash

# Arch dotfiles setup script
#
# Uses dotbot for dotfile install but this probably will be made into a custom dotfile manager soon
# Also can install needed packages

full=false
system=false
packages=false
dotfiles=false
extraScripts=false
mode="d"

help() {
	printf "Usage: $0 [OPTIONS] [script names]\n"
	printf "Argurments:\n"
	printf "  [script names]\n\tAn optional list of install scripts to run found in ./installScripts/."
	printf "\n\tTo run these scripts, pass in the '-e' option.\n\n"

	printf "Options:\n"
	printf "  -h\n\tShow this help message and exit\n"
	printf "  -f\n\tSetup the complete system. Equivalent to running $0 -s -p -d\n"
	printf "  -s\n\tConfigure system.\n"
	printf "  -p\n\tInstall system packages\n"
	printf "  -d\n\tInstall dotfiles\n"
	printf "  -e\n\tRun extra install scripts\n"
	printf "  -m MODE\n\tRun script in a specific mode. Possible modes are:\n\t'd': Desktop (default)\n\t'w': WSL\n\t'c': Dev Container\n"
}

setupSystem() {
	if [[ $mode == "d" ]]; then
		/usr/bin/env bash ./installScripts/desktop/system
	fi
}

setupPackages() {
	if [[ $mode == "d" ]]; then
		/usr/bin/env bash ./installScripts/desktop/packages
	fi
}

setupDotfiles() {
	if [[ $mode == "d" ]]; then
		dotbot -c ./installScripts/desktop/dotbot.conf.yaml
	elif [[ $mode == "w" ]]; then
		/usr/bin/env bash ./installScripts/wsl/setup
	elif [[ $mode == "c" ]]; then
		/usr/bin/env bash ./installScripts/container/setup
	fi
}

doFullInstall() {
	setupSystem
	setupPackages
	setupDotfiles
}

while getopts 'hfspdem:' opt; do
	case "$opt" in
		h) help; exit 0;;
		f) full=true;;
		s) system=true;;
		p) packages=true;;
		d) dotfiles=true;;
		e) extraScripts=true;;
		m) mode=${OPTARG};;
		*) help; exit 1;;
	esac
done

if [[ $full == true ]]; then
	doFullInstall
else
	if [[ $system == true ]]; then
		setupSystem
	fi
	if [[ $packages == true ]]; then
		setupPackages
	fi
	if [[ $dotfiles == true ]]; then
		setupDotfiles
	fi
fi

shift $(( OPTIND - 1 ))

if $extraScripts; then
	echo "Running extra scripts..."
	for scriptName in "$@"; do
		/usr/bin/env bash ./installScripts/$scriptName
	done
fi
