#!/usr/bin/env bash

echo "Installing packages..."

# Install packages
sudo pacman -S --noconfirm --needed neovim
sudo pacman -S --noconfirm --needed sudo
sudo pacman -S --noconfirm --needed git
sudo pacman -S --noconfirm --needed fish
sudo pacman -S --noconfirm --needed openssh
sudo pacman -S --noconfirm --needed ripgrep
sudo pacman -S --noconfirm --needed yazi
sudo pacman -S --noconfirm --needed keychain
sudo pacman -S --noconfirm --needed unzip
sudo pacman -S --noconfirm --needed wget
sudo pacman -S --noconfirm --needed fd
sudo pacman -S --noconfirm --needed jq
sudo pacman -S --noconfirm --needed fisher
sudo pacman -S --noconfirm --needed base-devel
sudo pacman -S --noconfirm --needed docker
sudo pacman -S --noconfirm --needed docker-buildx
sudo pacman -S --noconfirm --needed less
sudo pacman -S --noconfirm --needed go
sudo pacman -S --noconfirm --needed python3
sudo pacman -S --noconfirm --needed python-pip
sudo pacman -S --noconfirm --needed tk
sudo pacman -S --noconfirm --needed zellij
sudo pacman -S --noconfirm --needed fzf

# Install paru
if  pacman -Qi paru > /dev/null ; then
    paru -S --noconfirm --needed paru
else
    git clone https://aur.archlinux.org/paru.git $HOME/paru
    cd $HOME/paru
    makepkg -si --noconfirm --needed
fi

# Install AUR packages
paru -S --noconfirm --needed devpod-bin
