#!/usr/bin/env bash

# Make sure directories exist
mkdir -p $HOME/.config

# Make sure old configuration is deleted
rm -rf $HOME/.config/nvim $HOME/.config/fish
rm -rf $HOME/.local/bin

# Copy over configuration
cp ../../nvim $HOME/.config/nvim -r
cp ../../fish $HOME/.config/fish -r

cp ../../scripts/wsl $HOME/.local/bin -r
