#!/usr/bin/env bash

mkdir -p $HOME/.config

# Make sure old configuration is deleted
rm -rf $HOME/.config/nvim $HOME/.config/fish

# Copy over configuration
cp ../../nvim $HOME/.config/nvim -r
cp ../../fish $HOME/.config/fish -r
