#!/usr/bin/env bash

# This script runs all post install commands
# FOR THE USER ONLY
# eg. ONLY DOTFILE RELATED STUFF
# NOTHING FOR FULL SYSTEM CONFIGURATION
# USE TalinTheDev/Notes (private repo) FOR THOSE COMMMANDS


# Git config
read -p "Enter git email adddress: " gitEmail
read -p "Enter git full name: " gitName

git config --global user.email "$gitEmail"
git config --global user.name "$gitName"
git config --global diff.tool "nvimdiff"

# Fish config
chsh -s /usr/bin/fish
echo "To set the default fish greeting to nothing, run this command in a fish prompt:"
echo "    set -U fish_greeting \"\""

# Node.js
echo "To install Node.js, run the following commands in a fish prompt:"
echo "    fisher install jorgebucaran/nvm.fish"
echo "    nvm install latest"
echo "    corepack enable pnpm"

# SSH
echo "To setup SSH key configuration, run the following command and follow the steps. Then, add the key to http://github.com/settings/keys"
echo "    ssh-keygen -t ed25519 -C $gitEmail"

# Docker & Devpod setup
/usr/bin/env bash ./scripts/wsl/docker-setup

devpod-cli provider set-options -o "DOCKER_HOST=tcp://127.0.0.1:2375"
devpod-cli provider set-options -o "DOCKER_PATH=docker"
devpod-cli provider add docker
devpod-cli ide use none
devpod-cli context set-options -o DOTFILES_URL=git@github.com:TalinTheDev/dotfiles -o DOTFILES_SCRIPT="setup -f -m c"
