exec-once = sh ~/.config/scripts/init.sh
exec = sh ~/.config/scripts/wallpaper.sh
exec = sh ~/.config/scripts/waybar.sh

exec-once = swayidle -w timeout 300 "sh ~/.config/scripts/setBrightness.sh 100%" resume "sh ~/.config/scripts/setBrightness.sh 0%"
exec-once = swayidle -w timeout 600 "swaylock -f"
exec-once = swayidle -w timeout 900 "systemctl suspend"
