$cards = $HOME/.config/wallpapers/cards.jpg
$personOnWall = $HOME/.config/wallpapers/person_on_wall.png

# preload = $cards
# preload = $personOnWall

wallpaper = /home/talin/.config/wallpapers/person_on_wall.png
