$cards = $HOME/.config/wallpapers/cards.jpg
$personOnWall = $HOME/.config/wallpapers/person_on_wall.png

# preload = $cards
# preload = $personOnWall

# wallpaper = {
#     monitor = eDP-1
#     path = /home/talin/.config/wallpapers/person_on_wall.png
# }
#
wallpaper {
    monitor = 
    path = ~/.config/wallpapers/person_on_wall.png
    fit_mode = cover
}
