#!/usr/bin/env bash

echo "Installing packages..."

# Install packages
sudo pacman -S --noconfirm --needed hyprland
sudo pacman -S --noconfirm --needed waybar 
sudo pacman -S --noconfirm --needed wofi 
sudo pacman -S --noconfirm --needed fish
sudo pacman -S --noconfirm --needed neovim
sudo pacman -S --noconfirm --needed yazi
sudo pacman -S --noconfirm --needed hyprpaper
sudo pacman -S --noconfirm --needed brightnessctl
sudo pacman -S --noconfirm --needed hyprsunset
sudo pacman -S --noconfirm --needed keychain
sudo pacman -S --noconfirm --needed wl-clipboard
sudo pacman -S --noconfirm --needed unzip
sudo pacman -S --noconfirm --needed wget
sudo pacman -S --noconfirm --needed fd
sudo pacman -S --noconfirm --needed jq
sudo pacman -S --noconfirm --needed fisher
sudo pacman -S --noconfirm --needed zellij
sudo pacman -S --noconfirm --needed ghostty
sudo pacman -S --noconfirm --needed fzf
sudo pacman -S --noconfirm --needed hyprlock
sudo pacman -S --noconfirm --needed grim
sudo pacman -S --noconfirm --needed slurp

# Install paru
if  pacman -Qi paru > /dev/null ; then
	paru -S --noconfirm --needed paru
else
	git clone https://aur.archlinux.org/paru.git $HOME/paru
	cd $HOME/paru
	makepkg -si --noconfirm --needed
fi

# Install AUR packages
paru -S --noconfirm --needed google-chrome clipse dotbot
