#! /bin/bash
function clamp {
	min=$1
	max=$2
	val=$3
    minval=$(( $val < $max ? $val : $max ))
    maxval=$(( $min > $minval ? $min : $minval ))
    notify-send "maxval" "$maxval"
}

direction=$1
current=$2
if test "$direction" = "down"
then
	target=($(clamp 1 10 $(($current+1))) - 2)
	echo "jumping to $target"
	hyprctl dispatch workspace $target
elif test "$direction" = "up"
then
	target=$(clamp 1 10 $(($current-1)))
	echo "jumping to $target"
	hyprctl dispatch workspace $target
fi