#! /bin/bash
function clamp {
	min=$1
	max=$2
	val=$3
    minval=$(( $val < $max ? $val : $max ))
    maxval=$(( $min > $minval ? $min : $minval ))
}

direction=$1
current=$2
if test "$direction" = "down"
then
	target=$(clamp 1 10 $(($current+1)))
	notify-send "target" "$target"
	hyprctl dispatch workspace $target
elif test "$direction" = "up"
then
	target=$(clamp 1 10 $(($current-1)))
	notify-send "target" "$target"
	hyprctl dispatch workspace $target
fi