#!/usr/bin/env bash

mkdir -p $HOME/.config

# Make sure old configuration is deleted
rm -rf $HOME/.config/nvim $HOME/.config/fish

# Copy over configuration
cp ../../nvim $HOME/.config/nvim -r
cp ../../fish $HOME/.config/fish -r

# Remove keychain setup b/c not needed
rm $HOME/.config/fish/conf.d/keychain.fish

# Make sure talin is the group/owner of /home/$USER
chown $USER:$USER $HOME -R
